//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zhftool.rc
//
#define IDS_PROJNAME                    100
#define IDS_BFF_TITLE                   101
#define IDB_JYJ1                        140
#define IDB_JYJ2                        141
#define IDB_JYJ3                        142
#define IDB_JYJ4                        143
#define IDD_FINDREPLACE                 144
#define IDD_SUPERTEXT                   145
#define IDD_STEXTSET                    146
#define IDD_PMT_SET_REPLACEBLOCK        147
#define IDD_INPUTTEXT                   148
#define IDD_CONVERTTEXT                 149
#define IDD_MODIFYTEXT                  150
#define IDD_EDITTEXT                    151
#define IDD_XLSTODWG                    152
#define IDD_GETXLSHEIGHT                153
#define IDD_CHANGEFILENAME              154
#define IDD_FINDREPLACEBLK              155
#define IDD_GETDIANLAN                  156
#define IDD_SHOWBLKATT                  157
#define IDD_SETBLKATT                   158
#define IDD_SETPLWIDTH                  159
#define IDC_RADIO_PMTRB_XHJ             250
#define IDC_RADIO_PMTRB_DC              251
#define IDC_RADIO_PMTRB_JYJ             252
#define IDC_RADIO_PMTRB_JCB             253
#define IDC_EDIT_PMTRB_XHJ_BLKNAME      254
#define IDC_BUTTON_PMTRB_XHJ_SEL        255
#define IDC_RADIO_PMTRB_JYJ1            256
#define IDC_RADIO_PMTRB_JY2             257
#define IDC_RADIO_PMTRB_JYJ3            258
#define IDC_RADIO_PMTRB_JYJ4            259
#define ID_INT_EDIT                     260
#define IDC_CHECK_JYJWITHDIST           288
#define IDC_CHECK_RBSET_XHJWITHJYJ      289
#define IDC_EDIT_FILEPATH               290
#define IDC_CHECK_REG                   291
#define IDC_BUTTON_SELDIR               292
#define IDC_RADIO_SELECTION             293
#define IDC_RADIO_CURDWG                294
#define IDC_RADIO_FILEPATH              295
#define IDC_EDIT_XLSTODWG_FILEPATH      296
#define IDC_BUTTON_XLSTODWG_SELECTFILE  297
#define IDC_EDIT_XLSTODWG_STARTROW      298
#define IDC_EDIT_XLSTODWG_ENDROW        299
#define IDC_EDIT_XLSTODWG_STARTCOL      300
#define IDC_EDIT_XLSTODWG_ENDCOL        301
#define IDC_EDIT_XLSTODWG_MARKTEXT      302
#define IDC_RADIO_XLSTODWG_TRANSMODE_ALL 303
#define IDC_RADIO_XLSTODWG_TRANSMODE_SPECIAL 304
#define IDC_EDIT_GETHW_CAD_H            305
#define IDC_EDIT_GETHW_CAD_W            306
#define IDC_EDIT_GETHW_EXCEL_H          307
#define IDC_EDIT_GETHW_EXCEL_W          308
#define IDC_BUTTON_GETHW_DONE           309
#define IDC_MODIFYTEXT_RADIO1           310
#define IDC_MODIFYTEXT_RADIO2           311
#define IDC_STATIC_MSG                  312
#define IDC_MODIFYTEXT_RADIO3           313
#define IDC_MODIFYTEXT_RADIO4           314
#define IDC_MODIFYTEXT_RADIO5           315
#define IDC_MODIFYTEXT_RADIO6           316
#define IDC_MODIFYTEXT_RADIO7           317
#define IDC_MODIFYTEXT_RADIO8           318
#define IDC_MODIFYTEXT_RADIO9           319
#define IDC_MODIFYTEXT_EDIT1            320
#define IDC_ConFirm                     321
#define IDC_RADIO_STEXT_PICK            322
#define IDC_COMBO_ColorIndex            323
#define IDC_RADIO_STEXT_WINDOW          324
#define IDC_RADIO_TRANSTEXT_PART        325
#define IDC_RADIO_TRANSTEXT_GLOB        326
#define IDC_EDIT_WidthFactor            327
#define IDC_EDIT_StartNum               328
#define IDC_EDIT_Rotation               329
#define IDC_EDIT_Repeat                 330
#define IDC_COMBO_COLOR                 331
#define IDC_EDIT_INPUTTEXT_Y_OFFSET     332
#define IDC_CHECK_CASE                  333
#define IDC_EDIT_INPUTTEXT_X_OFFSET     334
#define IDC_EDIT_INPUTTEXT_WIDTH        335
#define IDC_EDIT_FIND                   336
#define IDC_EDIT_INPUTTEXT_TEXT         337
#define IDC_EDIT_REPLACE                338
#define IDC_EDIT_INPUTTEXT_ROTATION     339
#define IDC_EDIT_INPUTTEXT_HEIGHT       340
#define IDC_EDIT_IncreNum               341
#define IDC_EDIT_Height                 342
#define IDC_EDIT_FrontTxt               343
#define IDC_EDIT_BATCHTEXT_START        344
#define IDC_EDIT_BATCHTEXT_REPEAT       345
#define IDC_EDIT_BATCHTEXT_INCREMENT    346
#define IDC_EDIT_BATCHTEXT_FRONT        347
#define IDC_EDIT_BATCHTEXT_END          348
#define IDC_EDIT_BATCHTEXT_BACK         349
#define IDC_EDIT_BackTxt                350
#define IDC_COMBOIDC_INPUTTEXT_JUSTIFY  351
#define IDC_COMBO_STYLE                 352
#define IDC_COMBO_JUSTIFY               353
#define IDC_COMBO_INPUTTEXT_STYLE       354
#define IDC_COMBO_INPUTTEXT_COLOR       355
#define IDC_CHECK_SET                   356
#define IDC_CHECK_INPUTTEXT_SET         357
#define IDC_BUTTON_CONV_ATT             358
#define IDC_BUTTON_Ok                   359
#define IDC_BATCHTEXT_RADIO2            360
#define IDC_BATCHTEXT_RADIO1            361
#define IDC_RADIO_STEXT_X               362
#define IDC_RADIO_STEXT_Y               363
#define IDC_EDIT_CHANGEFILENAME_NEW     364
#define IDC_EDIT_CHANGEFILENAME_FILEPATH 365
#define IDC_COMBO_CHANGEFILENAME_EXT    366
#define IDC_EDIT_CHANGEFILENAME_OLD     367
#define IDC_BUTTON_CHANGEFILENAME_SELECT 368
#define IDC_BUTTON_GetDianlanDir        369
#define IDC_EDIT_DIANLANDIR             370
#define IDC_BUTTON_Do                   371
#define IDC_EDIT_FRB_FOLD               372
#define IDC_RADIO_FRB_SEL               373
#define IDC_RADIO_FRB_ALL               374
#define IDC_RADIO_FRB_FOLD              375
#define IDC_BUTTON_FRB_SELFOLD          376
#define IDC_BUTTON_FRB_SELNEWDWG        377
#define IDC_EDIT_FRB_ATT                378
#define IDC_CHECK_FRB_ATT               379
#define IDC_EDIT_GETDIANLAN_REG         380
#define IDC_CHECK_GETDIANLAN_MOREG      381
#define IDC_EDIT_SHOWBLKATT_BLKNAME     382
#define IDC_EDIT_SHOWBLKATT_ATTS        383
#define IDC_RADIO_SHOWBLKATT_SHOW       384
#define IDC_RADIO_SHOWBLKATT_HIDE       385
#define IDC_RADIO_GETDIANLAN_1          386
#define IDC_RADIO_GETDIANLAN_2          387
#define IDC_EDIT_GETDIANLAN_REG_LEN     388
#define IDC_EDIT_GETDIANLAN_REG_TYPE    389
#define IDC_COMBO_FRB_OLDBLK            390
#define IDC_COMBO_FRB_NEWBLK            391
#define IDC_RADIO_GETDIANLAN_2LINE      392
#define IDC_RADIO_GETDIANLAN_4LINE      393
#define IDC_COMBO_SETBLKATT_BLKNAME     394
#define IDC_RADIO_PMTRB_AP0             395
#define IDC_RADIO_PMTRB_AP1             396
#define IDC_RADIO_PMTRB_AP2             397
#define IDC_RADIO_PMTRB_YDQ0            398
#define IDC_RADIO_PMTRB_YDQ1            399
#define IDC_RADIO_PMTRB_YDQ2            400
#define IDC_RADIO_PMTRB_JZ0             401
#define IDC_RADIO_PMTRB_JZ1             402
#define IDC_RADIO_PMTRB_JZ2             403
#define IDC_RADIO_PMTRB_DHX             404
#define IDC_EDIT_SETPLWIDTH_FROM        405
#define IDC_EDIT_SETPLWIDTH_TO          406
#define IDC_CHECK1                      407
#define IDC_CHECK_SETPLWIDTH_INCLUDEBLK 407

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         408
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
