//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by blkcad.rc
//
#define IDS_PROJNAME                    100
#define IDS_PROJNAME2                   101
#define IDS_BFF_TITLE_MXB               102
#define IDS_BFF_TITLE                   103
#define IDD_LOCTONAME                   137
#define IDD_EDITFREQ                    147
#define IDD_MAXUBIAO                    148
#define IDD_INSERTGUIDAO                149
#define IDD_DLPX                        151
#define IDD_DLPX_INPUTFXP               152
#define IDD_STATION_SET                 155
#define IDD_LKDATA_SET                  156
#define IDD_CON_NODE                    160
#define IDD_BTMXB                       161
#define IDD_READBZT                     162
#define IDD_READLKDATA                  163
#define IDD_READLKFORPMT                164
#define IDD_DMH_DOSET                   166
#define IDD_DMH_OPTIONS                 167
#define IDD_DLPX_SET                    169
#define IDD_DIALOG1                     171
#define IDB_BITMAP1                     172
#define IDB_BITMAP2                     173
#define IDC_EDIT_DLPX_SAVEPATH          1000
#define IDC_XLSFILENAME                 1000
#define IDC_BUTTON_DLPX_SELPATH         1001
#define IDC_DLPX_PROGRESS1              1002
#define IDC_BUTTON_SELFILE              1003
#define IDC_SELFILE                     1003
#define IDC_EDIT_FILEPATH               1004
#define IDC_COMBO_MODE                  1005
#define IDC_CHECK_REG                   1006
#define IDC_BUTTON_SELDIR               1007
#define IDC_RADIO_SELECTION             1008
#define IDC_RADIO_CURDWG                1009
#define IDC_RADIO_FILEPATH              1010
#define IDC_EDIT_DWGNUM                 1011
#define IDC_BUTTON_SEL                  1012
#define IDC_EDIT_BAOFFSET               1013
#define IDC_EDIT_LINENAME               1014
#define IDC_BUTTON_SELPATH              1015
#define IDC_EDIT_XLSTODWG_FILEPATH      1016
#define IDC_STATIC_BAOFFSET             1017
#define IDC_BUTTON_XLSTODWG_SELECTFILE  1018
#define IDC_EDIT_XLSTODWG_STARTROW      1019
#define IDC_EDIT_XLSTODWG_ENDROW        1020
#define IDC_EDIT_XLSTODWG_STARTCOL      1021
#define IDC_LOCTONAME_SHEET             1021
#define IDC_EDIT_XLSTODWG_ENDCOL        1022
#define IDC_LOCTONAME_RADIO2            1022
#define IDC_EDIT_XLSTODWG_MARKTEXT      1023
#define IDC_LOCTONAME_RADIO1            1023
#define IDC_RADIO_XLSTODWG_TRANSMODE_ALL 1024
#define IDC_LOCTONAME_OUTROW            1024
#define IDC_RADIO_XLSTODWG_TRANSMODE_SPECIAL 1025
#define IDC_LOCTONAME_OUTCOL            1025
#define IDC_EDIT_GETHW_CAD_H            1026
#define IDC_LOCTONAME_INROW             1026
#define IDC_EDIT_GETHW_CAD_W            1027
#define IDC_LOCTONAME_INCOL             1027
#define IDC_EDIT_GETHW_EXCEL_H          1028
#define IDC_EDIT_GETHW_EXCEL_W          1029
#define IDC_BUTTON_GETHW_DONE           1030
#define IDC_MODIFYTEXT_RADIO1           1031
#define IDC_MODIFYTEXT_RADIO2           1032
#define IDC_STATIC_MSG                  1033
#define IDC_MODIFYTEXT_RADIO3           1034
#define IDC_MODIFYTEXT_RADIO4           1035
#define IDC_MODIFYTEXT_RADIO5           1036
#define IDC_MODIFYTEXT_RADIO6           1037
#define IDC_MODIFYTEXT_RADIO7           1038
#define IDC_MODIFYTEXT_RADIO8           1039
#define IDC_MODIFYTEXT_RADIO9           1040
#define IDC_MODIFYTEXT_EDIT1            1041
#define IDC_ConFirm                     1042
#define IDC_RADIO_STEXT_PICK            1043
#define IDC_COMBO_ColorIndex            1044
#define IDC_RADIO_STEXT_WINDOW          1045
#define IDC_RADIO_TRANSTEXT_PART        1046
#define IDC_RADIO_TRANSTEXT_GLOB        1047
#define IDC_EDIT_StationName            1048
#define IDC_EDIT_WidthFactor            1049
#define IDC_BUTTON_SelectDir            1050
#define IDC_EDIT_StartNum               1051
#define IDC_EDIT_Rotation               1052
#define IDC_EDIT_Repeat                 1053
#define IDC_EDIT_OldBlockName           1054
#define IDC_EDIT_NewBlockName           1055
#define IDC_COMBO_COLOR                 1056
#define IDC_EDIT_INPUTTEXT_Y_OFFSET     1057
#define IDC_CHECK_CASE                  1058
#define IDC_EDIT_INPUTTEXT_X_OFFSET     1059
#define IDC_EDIT_INPUTTEXT_WIDTH        1060
#define IDC_EDIT_FIND                   1061
#define IDC_EDIT_INPUTTEXT_TEXT         1062
#define IDC_EDIT_REPLACE                1063
#define IDC_EDIT_INPUTTEXT_ROTATION     1064
#define IDC_EDIT_INPUTTEXT_HEIGHT       1065
#define IDC_EDIT_IncreNum               1066
#define IDC_EDIT_Height                 1067
#define IDC_EDIT_FrontTxt               1068
#define IDC_EDIT_BATCHTEXT_START        1069
#define IDC_EDIT_BATCHTEXT_REPEAT       1070
#define IDC_EDIT_BATCHTEXT_INCREMENT    1071
#define IDC_EDIT_BATCHTEXT_FRONT        1072
#define IDC_EDIT_BATCHTEXT_END          1073
#define IDC_EDIT_BATCHTEXT_BACK         1074
#define IDC_EDIT_BackTxt                1075
#define IDC_COMBOIDC_INPUTTEXT_JUSTIFY  1076
#define IDC_COMBO_STYLE                 1077
#define IDC_COMBO_JUSTIFY               1078
#define IDC_COMBO_INPUTTEXT_STYLE       1079
#define IDC_COMBO_INPUTTEXT_COLOR       1080
#define IDC_CHECK_SET                   1081
#define IDC_CHECK_INPUTTEXT_SET         1082
#define IDC_CHECK_GLOBAL                1083
#define IDC_BUTTON_CONV_ATT             1084
#define IDC_BUTTON_SelectDwgFile        1085
#define IDC_BUTTON_Ok                   1086
#define IDC_BATCHTEXT_RADIO2            1087
#define IDC_BATCHTEXT_RADIO1            1088
#define IDC_LIST_FREQ                   1089
#define IDC_EDIT_SYT_HEIGHT             1090
#define IDC_EDIT_BETWEENTABLE           1091
#define IDC_EDIT_FRAMEHEIGHT            1092
#define IDC_EDIT_SAVEPATH               1093
#define IDC_COMBO_MAXUBIAO_TYPE         1094
#define IDC_EDIT_MXB_FONTWIDTH_GUIDAO   1095
#define IDC_EDIT_MXB_FONTHEIGHT_GUIDAO  1096
#define IDC_EDIT_MXB_FONTWIDTH_BIANMA   1097
#define IDC_EDIT_MXB_FONTHEIGHT_BIANMA  1098
#define IDC_DWGTHUMBNAILCTRL1           1099
#define IDC_DWGTHUMBNAILCTRL2           1100
#define IDC_DWGTHUMBNAILCTRL3           1101
#define IDC_DWGTHUMBNAILCTRL4           1102
#define IDC_DWGTHUMBNAILCTRL5           1103
#define IDC_DWGTHUMBNAILCTRL6           1104
#define IDC_DWGTHUMBNAILCTRL7           1105
#define IDC_DWGTHUMBNAILCTRL8           1106
#define IDC_DWGTHUMBNAILCTRL9           1107
#define IDC_DWGTHUMBNAILCTRL10          1108
#define IDC_DWGTHUMBNAILCTRL11          1109
#define IDC_DWGTHUMBNAILCTRL12          1110
#define IDC_DWGTHUMBNAILCTRL13          1111
#define IDC_DWGTHUMBNAILCTRL14          1112
#define IDC_DWGTHUMBNAILCTRL15          1113
#define IDC_DWGTHUMBNAILCTRL16          1114
#define IDC_DWGTHUMBNAILCTRL17          1115
#define IDC_DWGTHUMBNAILCTRL18          1116
#define IDC_DWGTHUMBNAILCTRL19          1117
#define IDC_DWGTHUMBNAILCTRL20          1118
#define IDC_EDIT_MXB_PROJNAME           1118
#define IDC_EDIT_MXB_DRAWNUM            1119
#define IDC_CON_NODE_TIE                1120
#define IDC_RADIO_CON_NODE_1            1121
#define IDC_RADIO_CON_NODE_2            1122
#define IDC_EDIT_BTMXB_STATION1         1123
#define IDC_EDIT_BTMXB_STATION2         1124
#define IDC_EDIT_BTMXB_SAVEPATH         1125
#define IDC_BUTTON_BTMXB_SELPATH        1126
#define IDC_RADIO_STEXT_X               1127
#define IDC_RADIO_STEXT_Y               1128
#define IDC_EDIT_READBZT_PATH           1129
#define IDC_EDIT_CHANGEFILENAME_NEW     1131
#define IDC_EDIT_READBZT_Z              1131
#define IDC_EDIT_CHANGEFILENAME_FILEPATH 1132
#define IDC_BUTTON_SELZ                 1132
#define IDC_EDIT_READBZT_Y              1133
#define IDC_COMBO_CHANGEFILENAME_EXT    1134
#define IDC_BUTTON_SELY                 1134
#define IDC_EDIT_CHANGEFILENAME_OLD     1135
#define IDC_EDIT_READBZT_ZH             1135
#define IDC_BUTTON_CHANGEFILENAME_SELECT 1136
#define IDC_BUTTON_SELZH                1136
#define IDC_EDIT_READBZT_G              1137
#define IDC_BUTTON_SELG                 1138
#define IDC_BUTTON_GetDianlanDir        1139
#define IDC_EDIT_READBZT_F              1139
#define IDC_EDIT_DIANLANDIR             1140
#define IDC_BUTTON_SELF                 1140
#define IDC_BUTTON_Do                   1141
#define IDC_EDIT_READLKDATA_FILEPATH    1141
#define IDC_EDIT_FRB_NEWBLK             1142
#define IDC_BUTTON_READLKDATA_SELDIR    1142
#define IDC_EDIT_FRB_OLDBLK             1143
#define IDC_EDIT_READLKDATA_CZXHJFILE   1143
#define IDC_EDIT_FRB_FOLD               1144
#define IDC_EDIT_READLKDATA_GDQDFILE    1144
#define IDC_RADIO_FRB_SEL               1145
#define IDC_EDIT_READLKDATA_DCXXFILE    1145
#define IDC_RADIO_FRB_ALL               1146
#define IDC_EDIT_READLKDATA_XLSDFILE    1146
#define IDC_RADIO_FRB_FOLD              1147
#define IDC_EDIT_READLKDATA_CZXXFILE    1147
#define IDC_BUTTON_FRB_SELFOLD          1148
#define IDC_EDIT_READLKDATA_PDXXFILE    1148
#define IDC_BUTTON_FRB_SELNEWDWG        1149
#define IDC_EDIT_READLKDATA_FXXXFILE    1149
#define IDC_BUTTON_READLKDATA_SELCZXHJ  1150
#define IDC_EDIT_FRB_ATT                1151
#define IDC_BUTTON_READLKDATA_SELGDQD   1151
#define IDC_CHECK_FRB_ATT               1152
#define IDC_BUTTON_READLKDATA_SELDCXX   1152
#define IDC_BUTTON_READLKDATA_SELXLSD   1153
#define IDC_BUTTON_READLKDATA_SELCZXX   1154
#define IDC_BUTTON_READLKDATA_SELPDXX   1155
#define IDC_BUTTON_READLKDATA_SELFXXX   1156
#define IDC_BUTTON_READLKDATA_SELQJXH   1159
#define IDC_EDIT_READLKDATA_QJXHFILE    1160
#define IDC_EDIT_READLKFORPMT_PATH      1161
#define IDC_BUTTON_READLKFORPMT_SELPATH 1162
#define IDC_EDIT_READLKFORPMT_XH        1163
#define IDC_BUTTON_READLKFORPMT_SELXH   1164
#define IDC_EDIT_READLKFORPMT_YDQ       1165
#define IDC_BUTTON_READLKFORPMT_SELYDQ  1166
#define IDC_RADIO_READLKFORPMT_1        1167
#define IDC_RADIO_READLKFORPMT_2        1168
#define IDC_CHECK_READLKFORPMT_SELXH    1169
#define IDC_CHECK_READLKFORPMT_SELYDQ   1170
#define IDC_STATIC_LKDATASET_NAME       1171
#define IDC_EDIT_GETDIANLAN_REG         1172
#define IDC_CHECK_GETDIANLAN_MOREG      1173
#define IDC_EDIT_SHOWBLKATT_BLKNAME     1174
#define IDC_EDIT_SHOWBLKATT_ATTS        1175
#define IDC_RADIO_SHOWBLKATT_SHOW       1176
#define IDC_RADIO_SHOWBLKATT_HIDE       1177
#define IDC_RADIO_GETDIANLAN_1          1178
#define IDC_RADIO_GETDIANLAN_2          1179
#define IDC_EDIT_DMH_SET_SAVEPATH       1180
#define IDC_PROGRESS_DMH_SET_ALL        1181
#define IDC_BUTTON_DMH_SET_SEL          1182
#define IDC_STATIC_DMH_PROGRESS         1183
#define IDC_EDIT_DMH_SET_CURITEM        1184
#define IDC_PROGRESS_DMH_SET_CUR        1185
#define IDC_RADIO_DMH_OPTION_TWOLINE    1186
#define IDC_RADIO_DMH_OPTION_FOURLINE   1187
#define IDC_RADIO_DMH_OPTION_FLONZH     1189
#define IDC_RADIO_DMH_OPTION_FLONFXP    1190
#define IDC_RADIO_DMH_OPTION_FLFROM1    1191
#define IDC_RADIO_DMH_OPTION_FLFROM2    1192
#define IDC_EDIT_DMH_OPTION_FXPSTART    1193
#define IDC_EDIT_DMH_OPTION_PREZ        1194
#define IDC_EDIT_DMH_OPTION_PREZY       1195
#define IDC_EDIT_DMH_OPTION_PREZZH      1196
#define IDC_EDIT_DMH_OPTION_NPLUSLOC    1197
#define IDC_COMBO1                      1198
#define IDC_COMBO_DMH_OPTION_FITFOR     1198
#define IDC_COMBO_DLPX_SET_XHJ_DC       1198
#define IDC_CHECK_DMH_OPTION_USEHLP     1199
#define IDC_EDIT_DMH_OPTION_PROJECTNAME 1200
#define IDC_EDIT_DMH_OPTION_DWGSN       1201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1206
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
